name: timmayd
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1914100358262658
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a9a9ab'
    - '#49362e'
    - '#c68324'
    - '#29c4e3'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
