name: timmayd
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1914100358262658
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efd7cd'
    - '#3a5357'
    - '#ccb3ac'
    - '#767676'
    - '#2d2727'
  brandStrength: 0.25
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
